// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsA4cJn4vQ1DvCkWCtrLoa-QeCL0a04l4',
    appId: '1:847235691076:web:c384633cccf6080e4a8211',
    messagingSenderId: '847235691076',
    projectId: 'orix-foods',
    authDomain: 'orix-foods.firebaseapp.com',
    storageBucket: 'orix-foods.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXEWPnjzem2rtA53pIaMFgla55920eXkU',
    appId: '1:847235691076:android:5e336a724dcc77174a8211',
    messagingSenderId: '847235691076',
    projectId: 'orix-foods',
    storageBucket: 'orix-foods.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq0WL37sbrVAYDOenQOgd9AvIoBEN8Pb8',
    appId: '1:847235691076:ios:d74103fe0e79cba94a8211',
    messagingSenderId: '847235691076',
    projectId: 'orix-foods',
    storageBucket: 'orix-foods.firebasestorage.app',
    iosBundleId: 'com.example.orixFood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAq0WL37sbrVAYDOenQOgd9AvIoBEN8Pb8',
    appId: '1:847235691076:ios:d74103fe0e79cba94a8211',
    messagingSenderId: '847235691076',
    projectId: 'orix-foods',
    storageBucket: 'orix-foods.firebasestorage.app',
    iosBundleId: 'com.example.orixFood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsA4cJn4vQ1DvCkWCtrLoa-QeCL0a04l4',
    appId: '1:847235691076:web:a1b66b6c14b6fb7d4a8211',
    messagingSenderId: '847235691076',
    projectId: 'orix-foods',
    authDomain: 'orix-foods.firebaseapp.com',
    storageBucket: 'orix-foods.firebasestorage.app',
  );
}
